#!/usr/bin/env bash
#
# Shell completion — print a completion artefact for wiring.
#
# Users can wire completion without knowing install paths: install.sh does it
# automatically, and this command is the manual path (plus the reinstall and
# upgrade paths). The artefacts under completions/ are GENERATED by
# scripts/gen-completion.sh from the grammar spec (`rp _complete-spec`) and
# ship in the release tarball.
#
# Usage: rp completion <bash|zsh>
#

# doc: bash
# Print the bash completion artefact to stdout.
#
# Usage: rp completion bash
#
# Notes:
#   Wire it into the current shell with: source <(rp completion bash)
#   To keep it, add that source line (or the installer's equivalent) to
#   ~/.bashrc. The artefact is bash 3.2+ — it runs in the INTERACTIVE shell,
#   which may be older than the Bash 5.1 rp itself requires.
#
# Examples:
# $ rp completion bash >> ~/.bashrc

# doc: zsh
# Print the zsh completion artefact to stdout.
#
# Usage: rp completion zsh
#
# Notes:
#   The artefact registers itself via compdef, which needs compinit to have
#   run — source it after compinit in ~/.zshrc:
#     rp completion zsh > "${HOME}/.rp/completions/_rp"
#   and add `source "${HOME}/.rp/completions/_rp"` to ~/.zshrc.
#
# Examples:
# $ rp completion zsh > "${HOME}/.rp/completions/_rp"

rp::cmd_completion() {
  local verb="${1:-help}"
  shift || true
  rp::args_parse "$@"
  rp::args_has help && verb=help
  local f
  case "$verb" in
  bash) _completion_artefact rp.bash ;;
  zsh) _completion_artefact _rp ;;
  -h | --help | help)
    cat <<'EOF'
Usage: rp completion <bash|zsh>

Print the generated shell completion artefact for a shell to stdout.
install.sh wires completion automatically; manual setup:

  bash: source <(rp completion bash)
  zsh:  rp completion zsh > "${HOME}/.rp/completions/_rp"
        then source that file from ~/.zshrc after compinit
EOF
    ;;
  *) rp::usage "unknown completion verb: '$verb' (try: rp completion --help)" ;;
  esac
}

# Print one artefact, naming the fix when this checkout/install predates the
# artefacts (an upgrade re-extracts them).
_completion_artefact() {
  local f="$RP_ROOT/completions/$1"
  [[ -f "$f" ]] ||
    rp::die "no completion artefact in this checkout or install ($f); re-run the rp installer"
  cat "$f"
}
