#!/usr/bin/env bash
#
# Shell completion — print a completion artefact for wiring.
#
# Users can wire completion without knowing install paths: install.sh does it
# automatically, and this command is the manual path (plus the reinstall and
# upgrade paths). The artefacts under completions/ are GENERATED by
# scripts/gen-completion.sh from the grammar spec (`rp _complete-spec`) and
# ship in the release tarball.
#
# Usage: rp completion <bash|zsh>
#

# doc: bash
# Print the bash completion bootstrap to stdout.
#
# Usage: rp completion bash
#
# Notes:
#   The output is a tiny lazy bootstrap: it registers a stub and sources the
#   full generated grammar only on the first `rp` TAB, so it never slows an
#   idle shell. Write it to a file and source that — a process substitution
#   would not resolve the grammar path:
#     rp completion bash > ~/.rp/completions/rp.lazy.bash
#     echo '[[ $- == *i* ]] && source ~/.rp/completions/rp.lazy.bash' >> ~/.bashrc
#   The installer does this for you. The artefact is bash 3.2+ — it runs in
#   the INTERACTIVE shell, which may be older than the Bash 5.1 rp requires.
#
# Examples:
# $ rp completion bash > ~/.rp/completions/rp.lazy.bash

# doc: zsh
# Print the zsh completion artefact to stdout.
#
# Usage: rp completion zsh
#
# Notes:
#   The artefact registers itself via compdef, which needs compinit to have
#   run — source it after compinit in ~/.zshrc:
#     rp completion zsh > "${HOME}/.rp/completions/_rp"
#   and add `source "${HOME}/.rp/completions/_rp"` to ~/.zshrc.
#
# Examples:
# $ rp completion zsh > "${HOME}/.rp/completions/_rp"

rp::cmd_completion() {
  local verb="${1:-help}"
  shift || true
  rp::args_parse "$@"
  rp::args_has help && verb=help
  local f
  case "$verb" in
  bash)
    # Emit the lazy bootstrap: a tiny stub that sources the full generated
    # grammar (rp.bash) only on the first `rp` TAB. The fallback path points
    # at this install's rp.bash so it also works via `source <(rp completion bash)`.
    cat <<EOF
# rp shell completion — lazy bootstrap (bash), emitted by \`rp completion bash\`.
# Sources the full generated grammar (rp.bash) only on the first \`rp\` TAB,
# so the grammar is never parsed in an idle shell.
_rp_bash_lazy() {
  unset -f _rp_bash_lazy
  local f
  f="\$(dirname "\${BASH_SOURCE[0]}")/rp.bash"
  [[ -f "\$f" ]] || f="$RP_ROOT/completions/rp.bash"
  source "\$f"
  type -t _rp >/dev/null 2>&1 && _rp "\$@"
}
complete -F _rp_bash_lazy rp
EOF
    ;;
  zsh) _completion_artefact _rp ;;
  -h | --help | help)
    cat <<'EOF'
Usage: rp completion <bash|zsh>

Print the shell completion bootstrap/artefact for a shell to stdout.
install.sh wires completion automatically; manual setup:

  bash: rp completion bash > ~/.rp/completions/rp.lazy.bash
        echo '[[ $- == *i* ]] && source ~/.rp/completions/rp.lazy.bash' >> ~/.bashrc
  zsh:  rp completion zsh > "${HOME}/.rp/completions/_rp"
        then source that file from ~/.zshrc after compinit
EOF
    ;;
  *) rp::usage "unknown completion verb: '$verb' (try: rp completion --help)" ;;
  esac
}

# Print one artefact, naming the fix when this checkout/install predates the
# artefacts (an upgrade re-extracts them).
_completion_artefact() {
  local f="$RP_ROOT/completions/$1"
  [[ -f "$f" ]] ||
    rp::die "no completion artefact in this checkout or install ($f); re-run the rp installer"
  cat "$f"
}
