#!/usr/bin/env bash
# gen-completion.sh — render the shell completion artefacts from the grammar
# spec (`rp _complete-spec`, lib/completion.sh). Output (committed):
#   completions/rp.bash   bash completion, bash 3.2+ (the interactive shell
#                         may be Apple's old bash even though rp needs 5.1)
#   completions/_rp       zsh completion, sourceable after compinit
#
# The artefacts embed the grammar verbatim, so TAB time never forks rp for
# the static surface; only live values (ids, cost centers) shell out to
# `rp _complete`. `make completions` regenerates; the pre-commit hook and CI
# regenerate-and-diff, so the artefacts cannot drift from the doc blocks.
#
# Env: RP_COMPLETION_OUT_DIR overrides the output directory (tests).
set -euo pipefail

RP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${RP_COMPLETION_OUT_DIR:-$RP_ROOT/completions}"

SPEC="$("$RP_ROOT/bin/rp" _complete-spec)"
[[ -n "$SPEC" ]] || {
  echo "gen-completion: empty grammar spec; aborting" >&2
  exit 1
}

# artefact_header <shell> — provenance banner on every generated file.
artefact_header() {
  printf '%s\n' \
    "# rp shell completion ($1) — GENERATED by scripts/gen-completion.sh." \
    "# Do not edit: regenerate with \`make completions\`. The grammar below is" \
    "# \`rp _complete-spec\` output; its source of truth is the \`# doc:\` blocks" \
    "# in commands/*.sh (parsed by lib/doc.sh)."
}

emit_bash() {
  local out="$1"
  {
    artefact_header bash
    # Embed the grammar single-quoted; descriptions carry apostrophes
    # ("runpodctl's"), so escape each one the standard '\'' way.
    printf '_rp_grammar=%s\n' "'$(printf '%s' "$SPEC" | sed "s/'/'\\\\''/g")'"
    cat <<'EOF'

# --- candidate helpers (bash 3.2+: no mapfile, no associative arrays) ---

# f-records for one resource+verb as "flag kind token" lines; verb-specific
# rows are seen before the "*" globals and !seen[] dedupes the overlap.
_rp_rows() { # $1 resource, $2 verb (may carry the group: "delegations list")
  awk -F'\t' -v r="$1" -v v="$2" \
    '$1 == "f" && ($2 == r || $2 == "*") && ($3 == v || $3 == "*") && !seen[$4]++ {print $4 "\t" $5 "\t" $6}' \
    <<<"$_rp_grammar"
}

_rp_resources() {
  awk -F'\t' '$1 == "v" {print $2}' <<<"$_rp_grammar" | LC_ALL=C sort -u
}

_rp_verbs() { # $1 resource; only single-word labels (group subs come separately)
  awk -F'\t' -v r="$1" '$1 == "v" && $2 == r && $3 !~ / / {print $3}' <<<"$_rp_grammar"
}

_rp_subs() { # $1 resource, $2 group verb
  awk -F'\t' -v r="$1" -v g="$2" \
    '$1 == "v" && $2 == r && index($3, g" ") == 1 {sub("^"g" ", "", $3); print $3}' \
    <<<"$_rp_grammar"
}

_rp_meta() { # $1 resource, $2 verb, $3 flag -> "kind token" ("" when unknown)
  _rp_rows "$1" "$2" | awk -F'\t' -v f="$3" '$1 == f {print $2 "\t" $3; exit}'
}

_rp_usage_token() { # $1 resource, $2 verb -> first positional <token> or ""
  awk -F'\t' -v r="$1" -v v="$2" \
    '$1 == "u" && $2 == r && $3 == v {if (match($4, /<[^>]*>/)) print substr($4, RSTART, RLENGTH); exit}' \
    <<<"$_rp_grammar"
}

_rp_is_group() { # $1 resource, $2 verb owns "group sub" v-records?
  awk -F'\t' -v r="$1" -v g="$2" \
    '$1 == "v" && $2 == r && index($3, g" ") == 1 {found = 1} END {exit !found}' \
    <<<"$_rp_grammar"
}

# Complete the VALUE of a value-flag: enum tokens split on "|", file-shaped
# tokens get filename completion, --cost-center asks rp for the local names.
_rp_complete_value() { # $1 res, $2 fullverb, $3 flag, $4 cur
  local meta kind token
  meta="$(_rp_meta "$1" "$2" "$3")"
  kind="${meta%%$'\t'*}"
  token="${meta#*$'\t'}"
  token="${token#<}"
  token="${token%>}"
  case "$token" in
  file* | path* | dir*) COMPREPLY=($(compgen -f -- "$4")) ;;
  *'|'*) COMPREPLY=($(compgen -W "${token//|/ }" -- "$4")) ;;
  *)
    [[ "$3" == "cost-center" ]] &&
      COMPREPLY=($(compgen -W "$(rp _complete "$1" "$2" cost-center 2>/dev/null)" -- "$4"))
    ;;
  esac
}

# Complete the FIRST positional from the usage record's <token>: id-shaped
# positions ask rp (cached ids/names), file-shaped ones get filenames.
_rp_complete_positional() { # $1 res, $2 fullverb, $3 cur
  local token
  token="$(_rp_usage_token "$1" "$2")"
  token="${token#<}"
  token="${token%>}"
  case "$token" in
  id | endpoint | name)
    COMPREPLY=($(compgen -W "$(rp _complete "$1" "$2" - 2>/dev/null)" -- "$3"))
    ;;
  file* | path* | dir*) COMPREPLY=($(compgen -f -- "$3")) ;;
  esac
}

_rp() {
  COMPREPLY=()
  local cur="${COMP_WORDS[COMP_CWORD]}"
  [[ -n "$_rp_grammar" ]] || return 0

  # Walk the typed words: resource, verb, sub-verb, positional count. A
  # non-flag word right after a value flag belongs to that flag, not to the
  # grammar; "--" ends the flags.
  local i w res="" verb="" sub="" npos=0 skip=0 lastflag="" meta kind token
  local fullverb
  for ((i = 1; i < COMP_CWORD; i++)); do
    w="${COMP_WORDS[i]}"
    case "$w" in
    --)
      npos=999
      skip=0
      ;;
    -*)
      fullverb="$verb${sub:+ $sub}"
      if [[ -n "$res" && -n "$fullverb" ]]; then
        meta="$(_rp_meta "$res" "$fullverb" "${w#--}")"
        kind="${meta%%$'\t'*}"
      else
        kind=""
      fi
      if [[ "$kind" == "value" ]]; then
        skip=1
        lastflag="${w#--}"
      else
        skip=0
      fi
      ;;
    *)
      if ((skip)); then
        skip=0
        continue
      fi
      if [[ -z "$res" ]]; then
        res="$w"
      elif [[ -z "$verb" ]]; then
        verb="$w"
      elif [[ -z "$sub" && -n "$verb" ]] && _rp_is_group "$res" "$verb"; then
        sub="$w"
      else
        npos=$((npos + 1))
      fi
      ;;
    esac
  done
  fullverb="$verb${sub:+ $sub}"

  if ((skip)); then
    _rp_complete_value "$res" "$fullverb" "$lastflag" "$cur"
    return 0
  fi

  case "$cur" in
  -*)
    [[ -n "$res" && -n "$fullverb" ]] &&
      COMPREPLY=($(compgen -W "$(_rp_rows "$res" "$fullverb" | awk -F'\t' '{print "--"$1}')" -- "$cur"))
    ;;
  *)
    if [[ -z "$res" ]]; then
      COMPREPLY=($(compgen -W "$(_rp_resources)" -- "$cur"))
    elif [[ -z "$verb" ]]; then
      COMPREPLY=($(compgen -W "$(_rp_verbs "$res")" -- "$cur"))
    elif [[ -z "$sub" && -n "$verb" ]] && _rp_is_group "$res" "$verb"; then
      COMPREPLY=($(compgen -W "$(_rp_subs "$res" "$verb")" -- "$cur"))
    elif ((npos == 0)); then
      _rp_complete_positional "$res" "$fullverb" "$cur"
    fi
    ;;
  esac
  return 0
}

# shellcheck disable=SC2120 # partial application is intentional below
complete -F _rp rp
EOF
  } >"$out"
}

emit_zsh() {
  local out="$1"
  {
    artefact_header zsh
    printf '%s\n' '#compdef rp'
    printf '_rp_grammar=%s\n' "'$(printf '%s' "$SPEC" | sed "s/'/'\\\\''/g")'"
    cat <<'EOF'
# Source AFTER compinit (e.g. from ~/.zshrc):  source /path/to/completions/_rp
# The grammar is embedded, so TAB time never forks rp for the static surface;
# live values (ids, cost centers) call `rp _complete` (cached, TTL 5 min).

_rp_rows() {
  awk -F'\t' -v r="$1" -v v="$2" \
    '$1 == "f" && ($2 == r || $2 == "*") && ($3 == v || $3 == "*") && !seen[$4]++ {print $4 "\t" $5 "\t" $6}' \
    <<<"$_rp_grammar"
}

_rp_resources() {
  awk -F'\t' '$1 == "v" {print $2}' <<<"$_rp_grammar" | LC_ALL=C sort -u
}

_rp_verbs() {
  awk -F'\t' -v r="$1" '$1 == "v" && $2 == r && $3 !~ / / {print $3}' <<<"$_rp_grammar"
}

_rp_subs() {
  awk -F'\t' -v r="$1" -v g="$2" \
    '$1 == "v" && $2 == r && index($3, g" ") == 1 {sub("^"g" ", "", $3); print $3}' \
    <<<"$_rp_grammar"
}

_rp_meta() {
  _rp_rows "$1" "$2" | awk -F'\t' -v f="$3" '$1 == f {print $2 "\t" $3; exit}'
}

_rp_usage_token() {
  awk -F'\t' -v r="$1" -v v="$2" \
    '$1 == "u" && $2 == r && $3 == v {if (match($4, /<[^>]*>/)) print substr($4, RSTART, RLENGTH); exit}' \
    <<<"$_rp_grammar"
}

_rp_is_group() {
  awk -F'\t' -v r="$1" -v g="$2" \
    '$1 == "v" && $2 == r && index($3, g" ") == 1 {found = 1} END {exit !found}' \
    <<<"$_rp_grammar"
}

# Filter a newline-separated candidate list by the literal prefix $2; the
# caller owns the loop (no bash-style namerefs in zsh).
# Stripped value token of a flag ("SECURE|COMMUNITY", "path|-", "type", "").
_rp_value_token() { # $1 res, $2 fullverb, $3 flag
  local meta token
  meta="$(_rp_meta "$1" "$2" "$3")"
  token="${meta#*$'\t'}"
  token="${token#<}"
  printf '%s' "${token%>}"
}

# Stripped first-positional token of a verb's usage record ("" when none).
_rp_positional_token() { # $1 res, $2 fullverb
  local token
  token="$(_rp_usage_token "$1" "$2")"
  token="${token#<}"
  printf '%s' "${token%>}"
}

_rp() {
  local cur="${words[CURRENT]}"
  local i w res="" verb="" sub="" npos=0 skip=0 lastflag="" meta kind token
  local fullverb cand
  local -a m
  for ((i = 2; i < CURRENT; i++)); do
    w="${words[i]}"
    case "$w" in
    --)
      npos=999
      skip=0
      ;;
    -*)
      fullverb="$verb${sub:+ $sub}"
      meta=""
      [[ -n "$res" && -n "$fullverb" ]] && meta="$(_rp_meta "$res" "$fullverb" "${w#--}")"
      kind="${meta%%$'\t'*}"
      if [[ "$kind" == "value" ]]; then
        skip=1
        lastflag="${w#--}"
      else
        skip=0
      fi
      ;;
    *)
      if ((skip)); then
        skip=0
        continue
      fi
      if [[ -z "$res" ]]; then
        res="$w"
      elif [[ -z "$verb" ]]; then
        verb="$w"
      elif [[ -z "$sub" && -n "$verb" ]] && _rp_is_group "$res" "$verb"; then
        sub="$w"
      else
        npos=$((npos + 1))
      fi
      ;;
    esac
  done
  fullverb="$verb${sub:+ $sub}"

  m=()
  if ((skip)); then
    # Completing the value of $lastflag. File-shaped tokens need _files in
    # this (completion) context — a $() capture would lose its output.
    token="$(_rp_value_token "$res" "$fullverb" "$lastflag")"
    local _nl=$'\n'
    case "$token" in
    file* | path* | dir*) _files -r '/' && return 0 ;;
    *'|'*) cand="${token//|/$_nl}" ;;
    *)
      [[ "$lastflag" == "cost-center" ]] &&
        cand="$(rp _complete "$res" "$fullverb" cost-center 2>/dev/null)"
      ;;
    esac
  elif [[ "$cur" == -* ]]; then
    [[ -n "$res" && -n "$fullverb" ]] &&
      cand="$(_rp_rows "$res" "$fullverb" | awk -F'\t' '{print "--"$1}')"
  elif [[ -z "$res" ]]; then
    cand="$(_rp_resources)"
  elif [[ -z "$verb" ]]; then
    cand="$(_rp_verbs "$res")"
  elif [[ -z "$sub" && -n "$verb" ]] && _rp_is_group "$res" "$verb"; then
    cand="$(_rp_subs "$res" "$verb")"
  elif ((npos == 0)); then
    token="$(_rp_positional_token "$res" "$fullverb")"
    case "$token" in
    file* | path* | dir*) _files -r '/' && return 0 ;;
    id | endpoint | name) cand="$(rp _complete "$res" "$fullverb" - 2>/dev/null)" ;;
    esac
  fi
  local c
  while IFS= read -r c; do
    [[ -z "$c" || "$c" != "$cur"* ]] && continue
    m+=("$c")
  done <<<"${cand:-}"
  ((${#m[@]})) && compadd -- "${m[@]}"
  return 0
}

# Sourcing this file registers the completion; the #compdef header above also
# allows an fpath install (copy to ~/.rp/completions and add that dir to
# $fpath before compinit).
compdef _rp rp 2>/dev/null || true
EOF
  } >"$out"
}

mkdir -p "$OUT_DIR"
emit_bash "$OUT_DIR/rp.bash"
emit_zsh "$OUT_DIR/_rp"
printf '%s\n' "$OUT_DIR/rp.bash" "$OUT_DIR/_rp"
