# rp shell completion — lazy bootstrap (bash).
# GENERATED by scripts/gen-completion.sh; do not edit. Static: it only
# sources the generated rp.bash on the first `rp` TAB.
_rp_bash_lazy() {
  unset -f _rp_bash_lazy
  source "$(dirname "${BASH_SOURCE[0]}")/rp.bash"
  type -t _rp >/dev/null 2>&1 && _rp "$@"
}
complete -F _rp_bash_lazy rp
