#!/usr/bin/env bash
# Generated completion artefacts (completions/rp.bash, completions/_rp).
# The drift guard is the point: artefacts are committed, so any grammar change
# (doc blocks, lib/completion.sh) must regenerate them in the same commit or
# this suite fails CI.
RP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BASH_ARTEFACT="$RP_ROOT/completions/rp.bash"
ZSH_ARTEFACT="$RP_ROOT/completions/_rp"

function set_up_before_script() {
  source "$RP_ROOT/lib/common.sh"
}

# --- existence + syntax ---

function test_should_have_generated_bash_artefact() {
  assert_file_exists "$BASH_ARTEFACT"
  assert_contains "GENERATED by scripts/gen-completion.sh" "$(<"$BASH_ARTEFACT")"
  assert_successful_code "$(bash -n "$BASH_ARTEFACT" 2>&1)"
}

function test_should_have_generated_zsh_artefact() {
  assert_file_exists "$ZSH_ARTEFACT"
  assert_successful_code "$(zsh -n "$ZSH_ARTEFACT" 2>&1)"
}

# --- drift: committed artefacts must equal a fresh regeneration ---

function test_should_regenerate_artefacts_byte_identical() {
  local tmp out
  tmp="$(mktemp -d)"
  RP_COMPLETION_OUT_DIR="$tmp" "$RP_ROOT/scripts/gen-completion.sh" >/dev/null
  assert_equals "$(<"$BASH_ARTEFACT")" "$(<"$tmp/rp.bash")"
  assert_equals "$(<"$ZSH_ARTEFACT")" "$(<"$tmp/_rp")"
  rm -rf "$tmp"
}

# --- bash smoke: simulate TAB presses against the generated function ---

# Run one simulated completion in a clean bash with the artefact sourced.
# Words (including the trailing empty "cur") come through as real argv, so an
# empty final word survives.
function _artefact_try() {
  bash --noprofile --norc -c '
    source "$0"
    COMP_WORDS=("$@"); COMP_CWORD=$((${#COMP_WORDS[@]}-1)); _rp
    printf "%s\n" "${COMPREPLY[*]:-}"
  ' "$BASH_ARTEFACT" "$@" 2>/dev/null
}

function test_should_complete_resources_verbs_and_flags() {
  local out
  out="$(_artefact_try rp "")"
  assert_contains "pod" "$out"
  assert_contains "cost-center" "$out"
  out="$(_artefact_try rp pod "")"
  assert_contains "create" "$out"
  out="$(_artefact_try rp pod create --c)"
  assert_contains "--cost-center" "$out"
  assert_contains "--cloud" "$out"
}

function test_should_complete_enum_values_statically() {
  local out
  out="$(_artefact_try rp pod create --cloud "")"
  assert_equals "SECURE COMMUNITY" "$out"
  out="$(_artefact_try rp serverless run --affinity "")"
  assert_equals "soft strict strict-resume" "$out"
}

function test_should_not_treat_value_words_as_positionals() {
  local out
  out="$(_artefact_try rp pod create --name mypod --gp)"
  assert_contains "--gpu" "$out"
}

# --- zsh smoke: stub the completion builtins, check the same surface ---

function test_should_complete_in_zsh() {
  command -v zsh >/dev/null 2>&1 || {
    bashunit::skip "zsh not available"
    return 0
  }
  local out
  out="$(zsh -f -c '
    compadd() { shift; reply=("$@"); }
    compdef() { :; }
    _files() { reply=(FILES); }
    rp() { :; }
    source '"$ZSH_ARTEFACT"'
    words=(rp pod create --cloud ""); CURRENT=$#words; reply=(); _rp
    printf "%s\n" "${reply[*]:-}"
  ' 2>/dev/null)"
  assert_equals "SECURE COMMUNITY" "$out"
}
